/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.hravemzdy.legalios.service

import com.github.michaelbull.result.Result
import com.github.michaelbull.result.Err
import com.github.michaelbull.result.Ok
import org.hravemzdy.legalios.factories.BundleBuilder
import org.hravemzdy.legalios.factories.IBundleBuilder
import org.hravemzdy.legalios.service.errors.HistoryResultError
import org.hravemzdy.legalios.interfaces.IBundleProps
import org.hravemzdy.legalios.interfaces.IPeriod

class ServiceLegalios : IServiceLegalios {
    private val builder : IBundleBuilder

    constructor() {
        builder = BundleBuilder()
    }

    override fun getBundle(period: IPeriod): Result<IBundleProps, HistoryResultError> {
        val bundle : IBundleProps? = builder.getBundle(period)

        if (bundle == null) {
            val error = HistoryResultError.BundleNoneError()
            return Err<HistoryResultError>(error)
        }
        if (bundle.getPeriodCode() == 0) {
            val error = HistoryResultError.BundleEmptyError()
            return Err<HistoryResultError>(error)
        }
        if (bundle.getPeriodCode() != period.code) {
            val error = HistoryResultError.BundleInvalidError()
            return Err<HistoryResultError>(error)
        }
        return Ok<IBundleProps>(bundle)
    }
}
